### ISSUE TITLE
Template cant handle multiple affiliations 

### ISSUE THREAD

**Issue by tractatus** [quarto-ext/typst-templates#2]
The IEEE template has a hard time handling quarto author affiliation input.
Also, do not handle flags such as `corresponding` or `equal-contributor`.

For example:
```
author:
  - name: Author One
    affiliations:
      - name: Harvard University
        id: a
        department: Department of Government
        city: Cambridge
        state: MA
        postal-code: 02138
      - name: Harvard University
        id: c
        department: Department of Statistics
        city: Cambridge
        state: MA
        postal-code: 02138
    attributes:
      equal-contributor: true
  - name: Author Two
    affiliations:
      - name: Yale University
        id: b
        department: Department of Political Science
        city: New Haven
        state: CT
        postal-code: 06511
    email: corresponding@email.com
    attributes:
      equal-contributor: true
      corresponding: true
 ```
